### PR TITLE
Fix problems with rate limit - updated

### PR DESCRIPTION
**Pull request by BrunoZell**
Since #1 is inactive, here is an updated PR.

- fix auto recreate 2 times the keys
- use file to validate time to recreate the keys
- create option to use STAGING_URL with environment IS_STAGING=1
- standalone-supported-challenges is deprecated

### CODE REVIEW

**Comment by BrunoZell** [comment]
Well, there is one problem:
When you host multiple web services under different domains, multiple certificates will be requested, sure.

But if you add a second web service **after** initially running the proxy, then only after the full week went by the initial certificate for the second domain is requested.

This `last_renewal.txt` needs to become domain-aware somehow so that when adding another web service the initial certificate for it is requested right away on startup.

@staticfloat @valdergallo @just1689

**Comment by staticfloat** [comment]
Just as an FYI, I didn't get an email from your edited-in pings.  :(  I think it doesn't trigger emails when you edit a comment.

What if we integrate the `last_renewal.txt` idea into the update loop and call it `${DOMAIN}.last_renewal.txt` so that we are tracking per-domain renewals?

**Comment by winiciuscota** [comment]
I which situation the key was being recreated twice? Is it possible to configure the image to store the key and other necessary info into a volume so that if you have to recreate the container the certbot would not try to get a new key?

**Comment by staticfloat** [comment]
I have found that storing `/etc/letsencrypt/live` as a volume does not work anymore, as the `live` directory now contains symlinks to files outside of the `live` directory, and that other files embed things like the hostname which means that when you start up a new docker container `letsencrypt` can get confused.

If someone wants to experiment and find the right `VOLUME` mapping to get `certbot` to remember the certs, but not get confused when things like the hostname change from invocation to invocation, we should definitely add those mappings to the `Dockerfile` as `VOLUME` instructions, and also add the volume mappings to the `docker-compose.yml` example file on `README.md`.

**Comment by BrunoZell** [comment]
I've set up per-domain tracking of renewal timestamps. Instead of creating a separate file for each domain to store the renewal timestamp, I just use the private key file for this domain. Seems simpler to me.

@staticfloat 
How have you discovered that the volume is no longer working correctly?

**Comment by staticfloat** [comment]
Looks good to me!  Thanks for the hard work everybody!

**Comment by staticfloat** [comment]
The volume problems were that I used to use `-v /etc/letsencrypt/live` to store my certificates between container sessions; however the storage layout of `certbot` changed a while ago, and so I was no longer able to do this, as the files within `/etc/letsencrypt/live` now are symlinks that point to files within `/etc/letsencrypt/archive`.  Perhaps it is sufficient to have two volumes, one for `/etc/letsencrypt/live` and one for `/etc/letsencrypt/archive`, but I haven't tested that.

Simply using `/etc/letsencrypt` as the volume mountpoint caused problems for me because of things like the hostname changing between invocations.  I don't know why, but apparently `letsencrypt` encodes the hostname into its state somewhere (doing a quick `grep` shows it within the `/etc/letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory` directory).

This shouldn't be a difficult thing to fix, it just takes someone motivated enough to try it out.

**Comment by niekoost** [comment]
I don't see an option to open up an issue or idea, that is why I chose this discussion since using multi-domain certificates also applies to rate limits [Rate-Limits and Duplicate Certificates - letsencrypt.org](https://letsencrypt.org/docs/rate-limits/)

What do you think about supporting multi-domain certificates? 
```
certbot ... -d example.com -d www.example.com ...
```
This could be activated by using a character (for instance, a comma) to separate the domains:
```
/etc/letsencrypt/live/example.com,www.example.com/fullchain.pem;
/etc/letsencrypt/live/example.com,www.example.com/privkey.pem;
```
Changes to `docker-nginx-certbot/src/scripts/util.sh` in the regular expressions, as well as a change to line 75 and the time stamping discussed in this PR might be necessary.

**Pull request merged**
