### PR TITLE
Enable support to subdomains

### PR DESCRIPTION
**Pull request by rodrigobraga**
Added one more parameter to generate a certificate valid to all subdomains

### CODE REVIEW

**Comment by staticfloat** [comment]
Can you please escape the * so that bash doesn’t get fancy and accidentally match against any files in the current directory that happen to end in $1.

**Comment by staticfloat** [comment]
Ah, I should have been more explicit. You need to add a backslash before the * :)

**Comment by rodrigobraga** [comment]
@staticfloat `-d \*.$1`is enough? #shellNoob :)

**Comment by staticfloat** [comment]
Yep! Although the quotes don’t hurt.

**Comment by staticfloat** [comment]
LGTM!  Thanks!

**Pull request merged**
