### PR TITLE
Compatibility fixes

### PR DESCRIPTION
**Pull request by gkosciolek**
Two changes that were needed to make this project running:

1. Fix the loop when iterating over domains. They need to be separated by space, not coma. Otherwise, this requests one certificate with all domain names glued together instead of a few individual certificates.

2. Remove the wildcard before the domain name. That is no longer supported with HTTP challenge.

### CODE REVIEW

**Comment by tomsvogel** [comment]
wating for this merge  👍 👍 thanks!

**Comment by jvanharn** [comment]
would really like this to be merged!

**Comment by surudoiryu** [comment]
+1

**Comment by staticfloat** [comment]
I very recently merged a PR that enabled the subdomain wildcard (#2).  Can you explain what the proper fix for fetching subdomain wildcards would be?

**Comment by gkosciolek** [comment]
According to the certbot docs, the DNS challenge is the only way to get wildcards certificates.

Please see the table few paragraphs below the beginning of the section:
https://certbot.eff.org/docs/using.html#getting-certificates-and-choosing-plugins

Therefore I do not think that there is an automated solution for wildcard certificates at this moment.

**Comment by staticfloat** [comment]
Perfect.  Thanks!

**Pull request merged**
